version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.4
jobs:
  pull:
    working_directory: ~/emojis
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Deps
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run script
          command: npm run start
      - run:
          name: Remove gitkeep
          command: rm ./static/.gitkeep
      - run:
          name: Zip artifacts
          command: tar -zcvf emojis.tar.gz static/
      - store_artifacts:
          path: emojis.tar.gz
      - persist_to_workspace:
          root: .
          paths:
            - static
            - emojis.tar.gz
  upload:
    working_directory: ~/emojis
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Set subdirectory datetime
          command: |
            echo 'export DATE="$(TZ=US/Central date "+%Y %m %d %H:%M:%S")"' >> $BASH_ENV
            source $BASH_ENV
      - aws-s3/copy:
          from: ./static
          to: '"s3://${S3_BUCKET}/${DATE}"'
          arguments: --recursive --acl public-read
      - aws-s3/copy:
          from: ./emojis.tar.gz
          to: '"s3://${S3_BUCKET}"'
          arguments: --acl public-read
workflows:
  version: 2
  tester:
    jobs:
      - pull
      - upload:
          requires:
            - pull
  weekly:
    triggers:
      - schedule:
          cron: "0 23 * * 5"
          filters:
            branches:
              only:
                - master
    jobs:
      - pull
      - upload:
          requires:
            - pull